# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-10 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogoAnalyzer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_logo_name', models.CharField(default='Unknown', max_length=200)),
                ('video', models.FileField(default='', upload_to='videos')),
                ('precision', models.CharField(default='0.0', max_length=20)),
            ],
        ),
    ]
